spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: MYSQL
    url: jdbc:mysql://localhost:3306/mysql



  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB  # Adjust max file size limit as needed
      max-request-size: 2MB  # Adjust max request size limit as needed
      file-size-threshold: 0
      location: /tmp  # Location to store uploaded files, optional
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8082

product-service:
 messages:
  categoryAdded: Category Added Successfully
  categoryAddErr: Failed to Add Category
  categoryUpdate: Category Updated Successfully
  categoryUpdateErr: Failed to update category
  categoryFetch: All Categories fetched successfully
  categoryFetchErr: Failed to fetch all categories
  categorySelect: Category Retrieved Successfully
  categorySelectErr: Failed to retrieve category
  categoryDelete: Category deleted successfully
  categoryDeleteErr: Failed to delete category
  productAdded: Product Added Successfully
  productAddErr: Failed to Add Product
  productUpdate: Product Updated Successfully
  productUpdateErr: Failed to update Product
  productFetch: All Products fetched successfully
  productFetchErr: Failed to fetch all Products
  productSelect: Product Retrieved Successfully
  productSelectErr: Failed to retrieve Product
  productDelete: Product deleted successfully
  productDeleteErr: Failed to delete Products
  loginErr: Invalid Credentials  
